version: "3.2"

services:
  yocto:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: build
        target: /build
        volume:
          nocopy: true
      - type: bind
        source: C:\Users\Dave\Projects\lora-gateway-os
        target: /lora-gateway-os
        volume:
          nocopy: true
          
  busybox:
    image: busybox
    volumes:
      - type: volume
        source: build
        target: /build
        volume:
          nocopy: true

volumes:
  build:
